## 1 Vectors and Vector Spaces
Vector:
- can be added together
- multiplied by scalars to produce another object of the same kind
Example:
- Geometric vectors
- Polynomials
- Audio signals
- Elements of $R^n$ (tuples of n real numbers)
![image.png](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/202505072355774.png)

## 2 Systems of Linear Equations

$$
\begin{bmatrix}
a_{11} \\
\vdots \\
a_{m1}
\end{bmatrix} x_1 +
\begin{bmatrix}
a_{12} \\
\vdots \\
a_{m2}
\end{bmatrix} x_2 +
\cdots +
\begin{bmatrix}
a_{1n} \\
\vdots \\
a_{mn}
\end{bmatrix} x_n =
\begin{bmatrix}
a_{11} & \cdots & a_{1n} \\
\vdots & \ddots & \vdots \\
a_{m1} & \cdots & a_{mn}
\end{bmatrix}
\begin{bmatrix}
x_1 \\
\vdots \\
x_n
\end{bmatrix}
=
\begin{bmatrix}
b_1 \\
\vdots \\
b_m
\end{bmatrix}
$$


## 3 Matrices
### 3.1 Matrix Addition and Multiplication


In [12]:
import numpy as np
# Matrix addiction
A = np.array([[1, 2, 3],
              [3, 2, 1]])  # Matrix A (2x3)
B = np.array([[3, 2, 1],
              [1, 2, 3]])  # Matrix B (2x3)

# Element-wise addition of matrices A and B
sum_result = A + B
print("Element-wise addition (A + B):\n", sum_result)

# Define a 3x2 matrix for matrix multiplication
C = np.array([[0, 2],
              [1, -1],
              [0, 1]])  # Matrix C (3x2)

# Matrix multiplication: A (2x3) · C (3x2) → result is 2x2
dot_result1 = np.dot(A, C)
print("Matrix multiplication (A · C):\n", dot_result1)

# Manual calculation for verification:
# A = [[1, 2, 3],
#      [3, 2, 1]]
# C = [[0, 2],
#      [1, -1],
#      [0, 1]]
# A·C =
# Row1: [1*0 + 2*1 + 3*0, 1*2 + 2*(-1) + 3*1] = [2, 3]
# Row2: [3*0 + 2*1 + 1*0, 3*2 + 2*(-1) + 1*1] = [2, 5]

# Matrix multiplication: C (3x2) · A (2x3) → result is 3x3
dot_result2 = np.dot(C, A)
print("Matrix multiplication (C · A):\n", dot_result2)

# Manual calculation of C · A:
# C = [[0, 2],
#      [1, -1],
#      [0, 1]]
# A = [[1, 2, 3],
#      [3, 2, 1]]
# C·A =
# Row1: [0*1 + 2*3, 0*2 + 2*2, 0*3 + 2*1]       = [6, 4, 2]
# Row2: [1*1 + (-1)*3, 1*2 + (-1)*2, 1*3 + (-1)*1] = [-2, 0, 2]
# Row3: [0*1 + 1*3, 0*2 + 1*2, 0*3 + 1*1]       = [3, 2, 1]

Element-wise addition (A + B):
 [[4 4 4]
 [4 4 4]]
Matrix multiplication (A · C):
 [[2 3]
 [2 5]]
Matrix multiplication (C · A):
 [[ 6  4  2]
 [-2  0  2]
 [ 3  2  1]]


### 3.2 Identity Matrix
**Definition:**
The **identity matrix** of size $n \times n$, denoted by $I_n$, is a square matrix where all the elements on the main diagonal are $1$, and all other elements are $0$.

Mathematically, the element in the $i$-th row and $j$-th column of $I_n$ is given by the Kronecker delta, $\delta_{ij}$:
$$(I_n)_{ij} = \delta_{ij} = \begin{cases} 1 & \text{if } i = j \\ 0 & \text{if } i \neq j \end{cases}$$

![image.png](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/202505081605400.png)

**Properties:**

![20250508224653](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/20250508224653.png)

### 3.3 Inverse matrix
**Defination:**

For a square $n \times n$ matrix $A$, an **inverse matrix**, denoted by $A^{-1}$, is an $n \times n$ matrix that satisfies the following condition:

$$A A^{-1} = I_n \quad \text{and} \quad A^{-1} A = I_n$$
If such a matrix $A^{-1}$ exists, the matrix $A$ is said to be **invertible** or **non-singular**.
**Remark:** Not all square matrices have an inverse. A square matrix that does not have an inverse is called **singular**.

![20250508230648](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/20250508230648.png)

So, A 2x2 matrix is invertible, only if $a_{11}a_{22} - a_{12}a_{21} \neq 0$.

**Properties:**

![20250508231532](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/20250508231532.png)

### 3.4 Multiplication by a Scalar

![20250508231741](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/20250508231741.png)

### 3.5 Solving Systems of Linear Equations
#### 3.5.1 
Steps:
1. Find a particular solution to Ax = b. 
2. Find all solutions to Ax = 0. 
3. Combine the solutions from steps 1. and 2. to the general solution.

In [7]:
import numpy as np
b = np.array([42,8])
A = np.array([[1,0,8,4],
              [0,1,2,12]])
print("Given matrix A:")
print(A)
print("\nGiven vector b:")
print(b)

# --- Step 1: Find a Particular Solution (xp) ---
print("\n--- Step 1: Finding a Particular Solution ---")

# Observe that the first two columns of matrix A are identity vectors.
# This allows us to easily find a particular solution by setting x3=0 and x4=0.
# The system then becomes:
# [1 0] [x1] = [42]
# [0 1] [x2] = [8]
# So one of the particular solutions is:
# [42,8,0,0]

# Construct the particular solution xp
xp = np.array([b[0], b[1], 0, 0])

print(f"\nA particular solution xp is:\n{xp.reshape(-1, 1)}")

# Verify the particular solution: Check if A @ xp equals b
print(f"\nVerification: A @ xp = {A @ xp.T} (should be equal to b = {b})")

# --- Step 1: Find a general Solution (x) ---
print("\n--- Step 2: Finding the General Solution ---")

# Find the null space of A
# The null space of A is the set of all solutions to Ax = 0.
# To find the null space, we need to solve the homogeneous system Ax = 0.
# The null space is the set of all solutions to this system.

# Extract column vectors
c1 = A[:, 0]
c2 = A[:, 1]
c3 = A[:, 2]
c4 = A[:, 3]

# Define the submatrix formed by the basis column vectors (corresponding to independent variables in the particular solution)
A_basis = A[:, :2] # This is [c1, c2]

print(f"\nSubmatrix A_basis formed by basis column vectors:\n{A_basis}")


# 1. For the third column c3
print("\n1. For the third column c3:")
# We want to solve k1*c1 + k2*c2 = c3
# Which is A_basis @ [k1, k2]^T = c3
coeffs_c3 = np.linalg.solve(A_basis, c3) # Solve for k1, k2

print(f"c3 = {c3} can be expressed as {coeffs_c3[0]} * c1 + {coeffs_c3[1]} * c2")
print(f"Verification: {coeffs_c3[0]} * {c1} + {coeffs_c3[1]} * {c2} = {coeffs_c3[0]*c1 + coeffs_c3[1]*c2}")

# This implies 8*c1 + 2*c2 - 1*c3 + 0*c4 = 0
# Therefore, a null space vector xn1 is [8, 2, -1, 0]^T
xn1 = np.array([coeffs_c3[0], coeffs_c3[1], -1, 0])

print(f"\nFirst null space basis vector xn1:\n{xn1.reshape(-1, 1)}")

# Verify if xn1 is in the null space (A @ xn1 should be the zero vector)
print(f"Verification: A @ xn1 = {A @ xn1.T} (should be equal to [0, 0])")


# 1. For the third column c4
print("\n2. For the fourth column c4:")
# We want to solve k1*c1 + k2*c2 = c4
# Which is A_basis @ [k1, k2]^T = c4
coeffs_c4 = np.linalg.solve(A_basis, c4) # Solve for k1, k2

print(f"c4 = {c4} can be expressed as {coeffs_c4[0]} * c1 + {coeffs_c4[1]} * c2")
print(f"Verification: {coeffs_c4[0]} * {c1} + {coeffs_c4[1]} * {c2} = {coeffs_c4[0]*c1 + coeffs_c4[1]*c2}")

# This implies 4*c1 + 12*c2 - 1*c4 + 0*c3 = 0
# Therefore, a null space vector xn2 is [4, 12, 0, -1]^T
xn2 = np.array([coeffs_c4[0], coeffs_c4[1], 0, -1])

print(f"\nSecond null space basis vector xn2:\n{xn2.reshape(-1, 1)}")       

# Verify if xn2 is in the null space (A @ xn2 should be the zero vector)
print(f"Verification: A @ xn2 = {A @ xn2.T} (should be equal to [0, 0])")

# --- Step 3: Combine to Form the General Solution (General Solution) ---
print("\n\n--- Step 3: Combining to Form the General Solution ---")

print("\nThe general solution for the system is:")
print("x = xp + λ1 * xn1 + λ2 * xn2")
print("\nWhere:")
print(f"xp = \n{xp.reshape(-1, 1)}")
print(f"\nxn1 = \n{xn1.reshape(-1, 1)}")
print(f"\nxn2 = \n{xn2.reshape(-1, 1)}")
print("\nWhere λ1, λ2 are arbitrary real numbers.")




Given matrix A:
[[ 1  0  8  4]
 [ 0  1  2 12]]

Given vector b:
[42  8]

--- Step 1: Finding a Particular Solution ---

A particular solution xp is:
[[42]
 [ 8]
 [ 0]
 [ 0]]

Verification: A @ xp = [42  8] (should be equal to b = [42  8])

--- Step 2: Finding the General Solution ---

Submatrix A_basis formed by basis column vectors:
[[1 0]
 [0 1]]

1. For the third column c3:
c3 = [8 2] can be expressed as 8.0 * c1 + 2.0 * c2
Verification: 8.0 * [1 0] + 2.0 * [0 1] = [8. 2.]

First null space basis vector xn1:
[[ 8.]
 [ 2.]
 [-1.]
 [ 0.]]
Verification: A @ xn1 = [0. 0.] (should be equal to [0, 0])

2. For the fourth column c4:
c4 = [ 4 12] can be expressed as 4.0 * c1 + 12.0 * c2
Verification: 4.0 * [1 0] + 12.0 * [0 1] = [ 4. 12.]

Second null space basis vector xn2:
[[ 4.]
 [12.]
 [ 0.]
 [-1.]]
Verification: A @ xn2 = [0. 0.] (should be equal to [0, 0])


--- Step 3: Combining to Form the General Solution ---

The general solution for the system is:
x = xp + λ1 * xn1 + λ2 * xn2

Whe

#### 3.5.2 Elementary Transformations

In [32]:
import numpy as np
b = np.array([2,5,1])
A = np.array([[1,2,-1],
              [2,5,2],
              [-1,-2,2]])

print("Given matrix A:")
print(A)
print("\nGiven vector b:")
print(b)
Ab = np.hstack([A,b.reshape(-1,1)])
print("Augmented matrix Ab:")
print(Ab)
# --- Step 1: Eliminate the first column ---
print("\n--- Step 1: Eliminate the first column ---")

# Subtract 2 times the first row from the second row
Ab[1] = Ab[1] - 2 * Ab[0]  

# Subtract 1 times the first row from the third row
Ab[2] = Ab[2] + 1 * Ab[0]

print("After eliminating the first column:")
print(Ab)

Given matrix A:
[[ 1  2 -1]
 [ 2  5  2]
 [-1 -2  2]]

Given vector b:
[2 5 1]
Augmented matrix Ab:
[[ 1  2 -1  2]
 [ 2  5  2  5]
 [-1 -2  2  1]]

--- Step 1: Eliminate the first column ---
After eliminating the first column:
[[ 1  2 -1  2]
 [ 0  1  4  1]
 [ 0  0  1  3]]


In [34]:
# --- Step 2: Eliminate the third column ---

Ab[0] = Ab[0] + Ab[2]

Ab[1] = Ab[1] - 4 * Ab[2]


print("After eliminating the third column:")
print(Ab)

After eliminating the third column:
[[  1   2   0   5]
 [  0   1   0 -11]
 [  0   0   1   3]]


In [35]:
# --- Step 3: Eliminate the second column ---

Ab[0] = Ab[0] - 2 * Ab[1]

print("After eliminating the third column:")
print(Ab)

After eliminating the third column:
[[  1   0   0  27]
 [  0   1   0 -11]
 [  0   0   1   3]]
