## 1 Vectors and Vector Spaces
Vector:
- can be added together
- multiplied by scalars to produce another object of the same kind
Example:
- Geometric vectors
- Polynomials
- Audio signals
- Elements of $R^n$ (tuples of n real numbers)
![image.png](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/202505072355774.png)

## 2 Systems of Linear Equations

$$
\begin{bmatrix}
a_{11} \\
\vdots \\
a_{m1}
\end{bmatrix} x_1 +
\begin{bmatrix}
a_{12} \\
\vdots \\
a_{m2}
\end{bmatrix} x_2 +
\cdots +
\begin{bmatrix}
a_{1n} \\
\vdots \\
a_{mn}
\end{bmatrix} x_n =
\begin{bmatrix}
a_{11} & \cdots & a_{1n} \\
\vdots & \ddots & \vdots \\
a_{m1} & \cdots & a_{mn}
\end{bmatrix}
\begin{bmatrix}
x_1 \\
\vdots \\
x_n
\end{bmatrix}
=
\begin{bmatrix}
b_1 \\
\vdots \\
b_m
\end{bmatrix}
$$


## 3 Matrices
### 3.1 Matrix Addition and Multiplication


In [12]:
import numpy as np
# Matrix addiction
A = np.array([[1, 2, 3],
              [3, 2, 1]])  # Matrix A (2x3)
B = np.array([[3, 2, 1],
              [1, 2, 3]])  # Matrix B (2x3)

# Element-wise addition of matrices A and B
sum_result = A + B
print("Element-wise addition (A + B):\n", sum_result)

# Define a 3x2 matrix for matrix multiplication
C = np.array([[0, 2],
              [1, -1],
              [0, 1]])  # Matrix C (3x2)

# Matrix multiplication: A (2x3) · C (3x2) → result is 2x2
dot_result1 = np.dot(A, C)
print("Matrix multiplication (A · C):\n", dot_result1)

# Manual calculation for verification:
# A = [[1, 2, 3],
#      [3, 2, 1]]
# C = [[0, 2],
#      [1, -1],
#      [0, 1]]
# A·C =
# Row1: [1*0 + 2*1 + 3*0, 1*2 + 2*(-1) + 3*1] = [2, 3]
# Row2: [3*0 + 2*1 + 1*0, 3*2 + 2*(-1) + 1*1] = [2, 5]

# Matrix multiplication: C (3x2) · A (2x3) → result is 3x3
dot_result2 = np.dot(C, A)
print("Matrix multiplication (C · A):\n", dot_result2)

# Manual calculation of C · A:
# C = [[0, 2],
#      [1, -1],
#      [0, 1]]
# A = [[1, 2, 3],
#      [3, 2, 1]]
# C·A =
# Row1: [0*1 + 2*3, 0*2 + 2*2, 0*3 + 2*1]       = [6, 4, 2]
# Row2: [1*1 + (-1)*3, 1*2 + (-1)*2, 1*3 + (-1)*1] = [-2, 0, 2]
# Row3: [0*1 + 1*3, 0*2 + 1*2, 0*3 + 1*1]       = [3, 2, 1]

Element-wise addition (A + B):
 [[4 4 4]
 [4 4 4]]
Matrix multiplication (A · C):
 [[2 3]
 [2 5]]
Matrix multiplication (C · A):
 [[ 6  4  2]
 [-2  0  2]
 [ 3  2  1]]


## 3.2 Identity Matrix
**Definition:**
The **identity matrix** of size $n \times n$, denoted by $I_n$, is a square matrix where all the elements on the main diagonal are $1$, and all other elements are $0$.

Mathematically, the element in the $i$-th row and $j$-th column of $I_n$ is given by the Kronecker delta, $\delta_{ij}$:
$$(I_n)_{ij} = \delta_{ij} = \begin{cases} 1 & \text{if } i = j \\ 0 & \text{if } i \neq j \end{cases}$$

![image.png](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/202505081605400.png)

**Properties:**

![20250508224653](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/20250508224653.png)

## 3.3 Inverse matrix
**Defination:**

For a square $n \times n$ matrix $A$, an **inverse matrix**, denoted by $A^{-1}$, is an $n \times n$ matrix that satisfies the following condition:

$$A A^{-1} = I_n \quad \text{and} \quad A^{-1} A = I_n$$
If such a matrix $A^{-1}$ exists, the matrix $A$ is said to be **invertible** or **non-singular**.
**Remark:** Not all square matrices have an inverse. A square matrix that does not have an inverse is called **singular**.

![20250508230648](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/20250508230648.png)

So, A 2x2 matrix is invertible, only if $a_{11}a_{22} - a_{12}a_{21} \neq 0$.

**Properties:**

![20250508231532](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/20250508231532.png)

## 3.4 Multiplication by a Scalar

![20250508231741](https://obsidian-1309699899.cos.ap-nanjing.myqcloud.com/20250508231741.png)
